
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 04 12:35:53 BOT 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int SEQ = 33;
  public static final int PLUSPLUS = 19;
  public static final int DOSPUNTOS = 32;
  public static final int BRACKETLEFT = 37;
  public static final int MULT = 21;
  public static final int CHAR = 56;
  public static final int CONST = 14;
  public static final int UMINUS = 43;
  public static final int CASE = 10;
  public static final int UNOT = 44;
  public static final int INT = 2;
  public static final int REF = 46;
  public static final int LESS = 25;
  public static final int FOR = 12;
  public static final int MINUS = 18;
  public static final int NOT = 31;
  public static final int AND = 30;
  public static final int OR = 29;
  public static final int BOOL = 4;
  public static final int DIV = 22;
  public static final int NUM = 52;
  public static final int TYPEDEF = 51;
  public static final int MOREEQ = 27;
  public static final int PLUS = 17;
  public static final int MAIN = 48;
  public static final int LESSEQ = 28;
  public static final int IF = 6;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 47;
  public static final int ASIG = 15;
  public static final int MINUSMINUS = 20;
  public static final int TRUE = 54;
  public static final int COMILLAS = 42;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int MOD = 23;
  public static final int BREAK = 5;
  public static final int VOID = 45;
  public static final int EQ = 16;
  public static final int PARRIGHT = 36;
  public static final int SWITCH = 9;
  public static final int CORRIGHT = 40;
  public static final int UNION = 49;
  public static final int ELSE = 8;
  public static final int BRACKETRIGHT = 38;
  public static final int PARLEFT = 35;
  public static final int WHILE = 13;
  public static final int DEFAULT = 11;
  public static final int FLOAT = 3;
  public static final int FALSE = 55;
  public static final int STRUCT = 50;
  public static final int CORLEFT = 39;
  public static final int ELIF = 7;
  public static final int MORE = 26;
  public static final int NOTEQ = 24;
  public static final int IDENTIFIER = 53;
}

